SELECT * FROM SCOTT.EMP;

SELECT*FROM SCOTT.DEPT;

SELECT MGR, SAL,EMPNO, ENAME,EMPNO FROM SCOTT.EMP;

SELECT SAL FROM SCOTT.EMP;
SELECT SUM(SAL) FROM SCOTT.EMP;

SELECT SUM(SAL), DEPTNO FROM SCOTT.EMP GROUP BY DEPTNO;



SELECT...;
INSERT...;
UPDATE...;
DELETE...;
DROP...;-- DELETE THE WHOLE TABLE --DELETE OBJECT ITSELF
CREATE...;
AS SELECT...; --SAME AS X
FROM X WHERE .. IN WANTED_RESULT;
-- * MEANS ALL


--CREATE UR OWN SCHEMA:-

CREATE TABLE EMP AS SELECT *FROM SCOTT.EMP;
CREATE TABLE BONUS AS SELECT *FROM SCOTT.BONUS;
CREATE TABLE SAL AS SELECT *FROM SCOTT.SALGRADE;
CREATE TABLE DEPT AS SELECT *FROM SCOTT.DEPT;
--//
--CREATE UR OWN SCHEMA:-
CREATE TABLE COUNTRIES AS SELECT * FROM HR.COUNTRIES;
CREATE TABLE DEPARTMENTS AS SELECT * FROM HR.DEPARTMENTS;
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE JOB_HISTORY AS SELECT * FROM HR.JOB_HISTORY;
CREATE TABLE JOBS AS SELECT * FROM HR.JOBS;
CREATE TABLE LOCATIONS AS SELECT * FROM HR.LOCATIONS;
CREATE TABLE REGIONS AS SELECT * FROM HR.REGIONS;
--//
SELECT * FROM employees; 
SELECT employee_id, first_name, email, hire_date, salary FROM employees;
SELECT hire_date, salary, employee_id, first_name, email FROM employees; 
SELECT salary, 12*(salary+100) FROM employees; 
SELECT DISTINCT department_id From employees;
SELECT last_name, salary FROM employees WHERE salary BETWEEN 2500 AND 3500;
SELECT last_name, manager_id FROM employees WHERE manager_id IN (100,101,201); 
SELECT first_name, salary FROM employees ORDER BY salary ASC;;
--//
SELECT SUM (1.12* SAL)FROM EMP;
